### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zhenyuanzhou** [Pythonpa/UniAnimate-GradioUI#2]
发生错误：Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/workspace/UniAnimate/webui.py", line 49, in process_video
    subprocess.run([
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1.

**Comment by zhenyuanzhou** [comment]
Incomplete downloaded models

**Comment by zhenyuanzhou** [comment]
![屏幕截图 2024-07-04 141212](https://github.com/Pythonpa/UniAnimate-GradioUI/assets/7355407/53ae76c5-0416-4b2c-b5ca-7aac6c418771)
![屏幕截图 2024-07-04 141225](https://github.com/Pythonpa/UniAnimate-GradioUI/assets/7355407/51d07c03-4707-4ce9-84a2-d5b8c868f1d1)
Please see attached

**Comment by Pythonpa** [comment]
> 发生错误：Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1. Traceback (most recent call last): File "/workspace/UniAnimate/webui.py", line 49, in process_video subprocess.run([ File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1.

First,  using the `exec` mode of Docker's containers ,and run the original command directly to see if it will report an error.
For example,`python run_align_pose.py  --ref_name data/images/musk.jpg --source_video_paths data/videos/source_video.mp4 --saved_pose_dir data/saved_pose/musk `.
Then ,check if you get a folder that containing pictures of extracted action frame  sequences.
And,use `python inference.py --cfg configs/UniAnimate_infer.yaml `,check if you get an error info.

**Comment by zhenyuanzhou** [comment]
I pulled the repository from the UniAnimate and found some files are missing in your package.
.\UniAnimate-GradioUI\tools\modules\unetunet_unianimate.py
\UniAnimate-GradioUI\tools\modules\util.py
